# Generated by Django 2.1 on 2018-08-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=128, null=True, verbose_name='Вопрос')),
                ('answer', models.CharField(blank=True, max_length=64, null=True, verbose_name='Ответ')),
                ('test_type', models.CharField(choices=[('input', 'Ввод'), ('radio', 'Выбор 1 ответа')], default='radio', max_length=64, verbose_name='Тип вопроса')),
                ('options', models.TextField(blank=True, default='', help_text='Впишите в это поле все варианты, включая верный, разделяя знаком ";"', null=True, verbose_name='Варианты')),
                ('image', models.FilePathField(blank=True, null=True, path='static/media/database/images', verbose_name='Иллюстрация')),
                ('anatomy', models.ForeignKey(blank=True, help_text='Оставьте это поле пустым, если нет', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.AnatomyElement', verbose_name='На основе анатомического элемента')),
                ('histology', models.ForeignKey(blank=True, help_text='Оставьте это поле пустым, если нет', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.HistologyElement', verbose_name='На основе гистологического элемента')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткая информация')),
                ('questions', models.ManyToManyField(to='test_app.Question', verbose_name='Вопросы')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
    ]
