# Generated by Django 2.1 on 2018-08-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0009_auto_20180813_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.TextField(blank=True, default='', help_text='Впишите в это поле все варианты, включая верный, разделяя знаком ";"', null=True, verbose_name='Варианты'),
        ),
    ]
