# Generated by Django 2.1 on 2018-08-29 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnatomyElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('lat_term', models.CharField(max_length=64, verbose_name='Латинский термин')),
                ('eng_term', models.CharField(blank=True, help_text='Необязательное поле', max_length=64, null=True, verbose_name='Английский термин')),
                ('info', models.TextField(blank=True, help_text='Разрешено использовать тэги HTML', null=True, verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Анатомия - элемент',
                'verbose_name_plural': 'Анатомия - элементы',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткая информация')),
                ('content', models.TextField(help_text='Разрешено использовать тэги HTML', verbose_name='Содержимое')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('is_main', models.BooleanField(default=True, verbose_name='Отображать на главной странице')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='ArticleTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('color', models.CharField(choices=[('primary', 'Фиолетовый'), ('info', 'Голубой'), ('success', 'Зеленый'), ('danger', 'Красный'), ('warning', 'Желтый'), ('default', 'Серый')], default='default', max_length=64, verbose_name='Цвет')),
                ('variable', models.SlugField(help_text='Указывать на английском языке, используя вместо пробелов знаки "_"', verbose_name='Переменная')),
            ],
            options={
                'verbose_name': 'Тема статьи',
                'verbose_name_plural': 'Темы статьи',
            },
        ),
        migrations.CreateModel(
            name='HistologyElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('lat_term', models.CharField(blank=True, help_text='Необязательное поле', max_length=64, null=True, verbose_name='Латинский термин')),
                ('eng_term', models.CharField(blank=True, help_text='Необязательное поле', max_length=64, null=True, verbose_name='Английский термин')),
            ],
            options={
                'verbose_name': 'Гистология - элемент',
                'verbose_name_plural': 'Гистология - элементы',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='database/images', verbose_name='Файл')),
                ('url', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ссылка')),
                ('code', models.CharField(blank=True, max_length=256, null=True, verbose_name='Код для вставки')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=128, null=True, verbose_name='Вопрос')),
                ('answer', models.CharField(blank=True, max_length=64, null=True, verbose_name='Ответ')),
                ('test_type', models.CharField(choices=[('input', 'Ввод'), ('radio', 'Выбор 1 ответа')], default='radio', max_length=64, verbose_name='Тип вопроса')),
                ('options', models.TextField(blank=True, default='', help_text='Впишите в это поле все варианты, включая верный, разделяя знаком ";"', null=True, verbose_name='Варианты')),
                ('anatomy', models.ForeignKey(blank=True, help_text='Оставьте это поле пустым, если нет', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.AnatomyElement', verbose_name='На основе анатомического элемента')),
                ('histology', models.ForeignKey(blank=True, help_text='Оставьте это поле пустым, если нет', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.HistologyElement', verbose_name='На основе гистологического элемента')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Image', verbose_name='Иллюстрация')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткая информация')),
                ('questions', models.ManyToManyField(to='database.Question', verbose_name='Вопросы')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.AddField(
            model_name='histologyelement',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Image', verbose_name='Иллюстрация'),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Image', verbose_name='Иллюстрация'),
        ),
        migrations.AddField(
            model_name='article',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.ArticleTheme', verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='anatomyelement',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Image', verbose_name='Иллюстрация'),
        ),
    ]
