# Generated by Django 2.1 on 2018-08-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anatomyelement',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='/static/media/database/images/', verbose_name='Иллюстрация'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='/static/media/database/images/', verbose_name='Иллюстрация'),
        ),
        migrations.AlterField(
            model_name='histologyelement',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='/static/media/database/images/', verbose_name='Иллюстрация'),
        ),
    ]
