# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-09 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anatomyelement',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.AnatomyType', verbose_name='Тип'),
        ),
    ]
