# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-11 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20180809_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='anatomygroup',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткая информация'),
        ),
        migrations.AddField(
            model_name='histologygroup',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткая информация'),
        ),
    ]
