# Generated by Django 2.1 on 2018-08-14 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20180814_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anatomyelement',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Image', verbose_name='Иллюстрация'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Image', verbose_name='Иллюстрация'),
        ),
        migrations.AlterField(
            model_name='histologyelement',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Image', verbose_name='Иллюстрация'),
        ),
    ]
