# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-11 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20180811_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('variable', models.SlugField(help_text='Указывать на английском языке, используя вместо пробелов знаки "_"', verbose_name='Переменная')),
            ],
            options={
                'verbose_name': 'Тема статьи',
                'verbose_name_plural': 'Темы статьи',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.ArticleTheme', verbose_name='Тема'),
        ),
    ]
