# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-11 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20180811_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletheme',
            name='color',
            field=models.CharField(choices=[('primary', 'Фиолетовый'), ('info', 'Голубой'), ('success', 'Зеленый'), ('danger', 'Красный'), ('warning', 'Желтый'), ('default', 'Серый')], default='default', max_length=64, verbose_name='Цвет'),
        ),
    ]
