# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-12 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_article_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='database/images', verbose_name='Файл')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.AlterField(
            model_name='anatomyelement',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='database/images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='histologyelement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='database/histology', verbose_name='Иллюстрация'),
        ),
    ]
