# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-12 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20180812_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='static/media/database/images', verbose_name='Иллюстрация'),
        ),
        migrations.AlterField(
            model_name='anatomyelement',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='static/media/database/images', verbose_name='Иллюстрация'),
        ),
        migrations.AlterField(
            model_name='histologyelement',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='static/media/database/images', verbose_name='Иллюстрация'),
        ),
    ]
