# Generated by Django 2.1 on 2018-08-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20180813_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='static/media/database/images/', verbose_name='Иллюстрация'),
        ),
    ]
