# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-09 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=128, null=True, verbose_name='Вопрос')),
                ('answer', models.CharField(blank=True, max_length=64, null=True, verbose_name='Ответ')),
                ('options', models.TextField(default='', help_text='Впишите в это поле все варианты, включая верный, разделяя знаком ";"', verbose_name='Все варианты')),
                ('image', models.ImageField(blank=True, null=True, upload_to='test/', verbose_name='Иллюстрация')),
                ('anatomy', models.ForeignKey(blank=True, help_text='Оставьте это поле пустым, если нет', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.AnatomyElement', verbose_name='На основе анатомического элемента')),
                ('histology', models.ForeignKey(blank=True, help_text='Оставьте это поле пустым, если нет', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.HistologyElement', verbose_name='На основе гистологического элемента')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('questions', models.ManyToManyField(to='test.Question', verbose_name='Вопросы')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
    ]
