# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-11 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_question_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='test_type',
            field=models.CharField(choices=[('input', 'Ввод'), ('radio', 'Выбор 1 ответа')], default='radio', max_length=64),
        ),
    ]
