# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-11 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_auto_20180811_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.TextField(default='', help_text='Впишите в это поле все варианты, включая верный, разделяя знаком ";"', verbose_name='Варианты'),
        ),
    ]
