# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-12 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0005_auto_20180811_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткая информация'),
        ),
    ]
