# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-12 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0007_auto_20180812_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='static/media/database/images', verbose_name='Иллюстрация'),
        ),
    ]
