# Generated by Django 2.1 on 2018-08-13 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0008_auto_20180812_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='anatomy',
            field=models.ForeignKey(blank=True, help_text='Оставьте это поле пустым, если нет', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.AnatomyElement', verbose_name='На основе анатомического элемента'),
        ),
        migrations.AlterField(
            model_name='question',
            name='histology',
            field=models.ForeignKey(blank=True, help_text='Оставьте это поле пустым, если нет', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.HistologyElement', verbose_name='На основе гистологического элемента'),
        ),
    ]
