# Generated by Django 2.1 on 2018-08-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnatomySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FilePathField(blank=True, null=True, path='static/media/database/images/', verbose_name='Обложка')),
                ('is_latin_test', models.BooleanField(default=False, verbose_name='Автоматический тест по латинским терминам')),
                ('articles', models.ManyToManyField(blank=True, to='database.Article', verbose_name='Статьи')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.AnatomyGroup', verbose_name='Группа')),
                ('tests', models.ManyToManyField(blank=True, to='test_app.Test', verbose_name='Тесты')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.AnatomyType', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Анатомия - секция',
                'verbose_name_plural': 'Анатомия - секции',
            },
        ),
        migrations.CreateModel(
            name='HistologySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FilePathField(blank=True, null=True, path='static/media/database/images/', verbose_name='Обложка')),
                ('is_latin_test', models.BooleanField(default=False, verbose_name='Автоматический тест по латинским терминам')),
                ('articles', models.ManyToManyField(blank=True, to='database.Article', verbose_name='Статьи')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.HistologyGroup', verbose_name='Группа')),
                ('tests', models.ManyToManyField(blank=True, to='test_app.Test', verbose_name='Тесты')),
            ],
            options={
                'verbose_name': 'Гистология - секция',
                'verbose_name_plural': 'Гистология - секции',
            },
        ),
    ]
