# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-09 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnatomySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/covers', verbose_name='Обложка')),
                ('is_latin_test', models.BooleanField(default=False, verbose_name='Автоматический тест по латинским терминам')),
                ('articles', models.ManyToManyField(blank=True, to='database.Article', verbose_name='Статьи')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.AnatomyGroup', verbose_name='Группа')),
                ('tests', models.ManyToManyField(blank=True, to='test.Test', verbose_name='Тесты')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.AnatomyType', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Анатомия - секция',
                'verbose_name_plural': 'Анатомия - секции',
            },
        ),
        migrations.CreateModel(
            name='HistologySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/covers', verbose_name='Обложка')),
                ('is_latin_test', models.BooleanField(default=False, verbose_name='Автоматический тест по латинским терминам')),
                ('articles', models.ManyToManyField(blank=True, to='database.Article', verbose_name='Статьи')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.HistologyGroup', verbose_name='Группа')),
                ('tests', models.ManyToManyField(blank=True, to='test.Test', verbose_name='Тесты')),
            ],
            options={
                'verbose_name': 'Гистология - секция',
                'verbose_name_plural': 'Гистология - секции',
            },
        ),
    ]
