# Generated by Django 2.1 on 2018-08-29 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnatomySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('variable', models.SlugField(verbose_name='')),
                ('content', models.TextField(help_text='...', verbose_name='Контент')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Image', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Раздел анатомии',
                'verbose_name_plural': 'Разделы анатомии',
            },
        ),
        migrations.CreateModel(
            name='HistologySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('variable', models.SlugField(verbose_name='')),
                ('content', models.TextField(help_text='...', verbose_name='Контент')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Image', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Раздел гистологии',
                'verbose_name_plural': 'Разделы гистологии',
            },
        ),
    ]
