# Generated by Django 2.1 on 2018-08-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anatomysection',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='/static/media/database/images/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='histologysection',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='/static/media/database/images/', verbose_name='Обложка'),
        ),
    ]
