# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-09 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anatomysection',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.AnatomyType', verbose_name='Тип'),
        ),
    ]
