# Generated by Django 2.1 on 2018-08-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anatomysection',
            name='variable',
            field=models.SlugField(help_text='Указывать на английском языке, используя вместо пробелов знаки "_"', verbose_name='Переменная'),
        ),
        migrations.AlterField(
            model_name='histologysection',
            name='variable',
            field=models.SlugField(help_text='Указывать на английском языке, используя вместо пробелов знаки "_"', verbose_name='Переменная'),
        ),
    ]
