# Generated by Django 2.1 on 2018-08-14 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180814_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anatomysection',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Image', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='histologysection',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Image', verbose_name='Обложка'),
        ),
    ]
