# Generated by Django 2.1 on 2018-08-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180830_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='anatomysection',
            name='articles_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество статей'),
        ),
        migrations.AddField(
            model_name='anatomysection',
            name='tests_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество тестов'),
        ),
    ]
