# Generated by Django 2.1 on 2018-08-13 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20180812_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anatomysection',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.AnatomyGroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='anatomysection',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.AnatomyType', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='histologysection',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.HistologyGroup', verbose_name='Группа'),
        ),
    ]
